### ISSUE TITLE
Add script(s) for fetching required dependencies?

### ISSUE THREAD

**Issue by vdice** [fermyon/nomad-local-demo#14]
Should we add script(s) that users can run to quickly fetch/install all required dependencies for the local scenario?

**Comment by dicej** [comment]
I'm certainly in favor of this, but I also realize making it work reliably on a range of OSes (even just a range of unix-style OSes) is a tough job.

Also, many people won't be comfortable running such a script, and/or will want an "undo" script to revert any changes, which would be even tougher to do well.

Ideally, we just wouldn't touch the host OS at all.

**Comment by lann** [comment]
Fixed in https://github.com/fermyon/installer/commit/2236a143e0f742c51386e35d2a9ab3026f2ec9c2
