### ISSUE TITLE
Support linux via `ip` or allow override

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/nomad-local-demo#6]
`ipconfig` is not present on most Linux distributions. Most distributions use `ip`.

https://github.com/fermyon/nomad-local-demo/blob/ce6a9183fe52ab340fa674110f21c87a7a9bb02e/run_servers.sh#L33

There should be a way to override this environment variable so that I can set $IP_ADDRESS before running the script.

**Comment by adamreese** [comment]
This hack it only required for MacOS and Windows.
